project:
  type: website
  output-dir: docs
  resources:
    - assets\styles\quarto.scss
    - assets\jspsych-favicon.png
execute:
  cache: true
format: dashboard
website:
  site-url: "https://smpdl.github.io/jsPsych-Dashboard/" 