on:
  push:
    branches:
      - main

name: build-dash

permissions:
  contents: write

jobs:
  build-dash:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - uses: actions/checkout@v3

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release

    - name: Cache targets data
      uses: actions/cache@v3
      with:
          path: _targets
          key: ${{ runner.os }}-targets-v1-${{ hashFiles('**/cache.log') }}
          restore-keys: |
              ${{ runner.os }}-targets-v1-
                
    - name: Publish to Quarto Pub
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: quarto-pub
        render: false
        path: index.qmd
        QUARTO_PUB_AUTH_TOKEN: ${{secrets.QUARTO_PUB_AUTH_TOKEN }}